# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug
endif
export config

PROJECTS := objectspace test

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

objectspace: 
	@echo "==== Building objectspace ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f objectspace.make

test: 
	@echo "==== Building test ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f test.make

clean:
	@${MAKE} --no-print-directory -C . -f objectspace.make clean
	@${MAKE} --no-print-directory -C . -f test.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug"
	@echo "   test"
	@echo "   production"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   objectspace"
	@echo "   test"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
